description: Tiny reversible text obfuscator for desktop and browser.
homepage: https://majkey25.github.io/ByteNoise/
topics:
  - python
  - tkinter
  - javascript
  - github-pages
  - text-obfuscation
